/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import {OrthographicCamera} from '@react-three/drei'
import Glider from '../components/Glider'
import {useRef} from 'react'
import {ControlTypes} from '../types/controls'
import CustomCamera from '../components/Camera'
import {useThree} from '@react-three/fiber'

export default function Scene({...props}) {
  const {nodes, materials} = useSpline('https://prod.spline.design/zbNFDumFMuwLUsXd/scene.splinecode')
  const gliderRef = useRef(null)
  const controlsType = ControlTypes.BASE
  const {camera} = useThree()
  const groundRef = useRef()
  return (
    <>
      <CustomCamera groundRef={groundRef} controlsType={controlsType} gliderRef={gliderRef} camera={camera} />
      <Glider gliderRef={gliderRef} isInLift={false} controlsType={controlsType} />
      <color attach="background" args={['#d2ebf4']} />
      <fog attach="fog" args={['#d2ebf4', 2500, 4227]} />
      <group {...props} dispose={null}>
        <mesh
          name="Ocean"
          geometry={nodes.Ocean.geometry}
          material={materials.Water}
          castShadow
          receiveShadow
          position={[46.83, -180.04, -3.21]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={1}
        />
        <group name="Light Post Door" position={[489.02, 374.86, -222.79]} ref={groundRef}>
          <mesh
            name="Ellipse 2"
            geometry={nodes['Ellipse 2'].geometry}
            material={materials['Ellipse 2 Material']}
            castShadow
            receiveShadow
            position={[16.69, 0.26, -6.82]}
            rotation={[-0.05, 0.44, -Math.PI / 2]}
            scale={1}
          />
          <mesh
            name="Rectangle 3"
            geometry={nodes['Rectangle 3'].geometry}
            material={materials['Rectangle 3 Material']}
            castShadow
            receiveShadow
            position={[0, -0.09, 0]}
            rotation={[-0.05, 0.44, -Math.PI / 2]}
            scale={1}
          />
        </group>
        <group name="Steps" position={[343.1, 261.1, -76.34]}>
          <mesh
            name="Cube 12"
            geometry={nodes['Cube 12'].geometry}
            material={materials.Pathway}
            castShadow
            receiveShadow
            position={[1.59, -63.45, 140.17]}
            rotation={[Math.PI, 1.35, Math.PI / 2]}
            scale={1}
          />
          <mesh
            name="Cube 11"
            geometry={nodes['Cube 11'].geometry}
            material={materials.Pathway}
            castShadow
            receiveShadow
            position={[-2.43, -45.12, 125.84]}
            rotation={[-Math.PI, 1.35, Math.PI / 2]}
            scale={1}
          />
          <mesh
            name="Cube 15"
            geometry={nodes['Cube 15'].geometry}
            material={materials.Pathway}
            castShadow
            receiveShadow
            position={[128.21, 50.45, -137.01]}
            rotation={[-Math.PI, 1.17, Math.PI / 2]}
            scale={1}
          />
          <mesh
            name="Cube 14"
            geometry={nodes['Cube 14'].geometry}
            material={materials.Pathway}
            castShadow
            receiveShadow
            position={[153.78, 43.51, -118.28]}
            rotation={[-Math.PI, 1.37, Math.PI / 2]}
            scale={1}
          />
          <mesh
            name="Cube 13"
            geometry={nodes['Cube 13'].geometry}
            material={materials.Pathway}
            castShadow
            receiveShadow
            position={[157.95, 12.13, -90.21]}
            rotation={[-Math.PI, 1.37, Math.PI / 2]}
            scale={1}
          />
          <mesh
            name="Cube 10"
            geometry={nodes['Cube 10'].geometry}
            material={materials.Pathway}
            castShadow
            receiveShadow
            position={[-19.43, -29.77, 97.41]}
            rotation={[-Math.PI, 1.37, Math.PI / 2]}
            scale={1}
          />
          <mesh
            name="Cube 9"
            geometry={nodes['Cube 9'].geometry}
            material={materials.Pathway}
            castShadow
            receiveShadow
            position={[-128.72, -37.21, 107.41]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          />
        </group>
        <group name="House Door" position={[197.79, 295.35, 21]}>
          <mesh
            name="Ellipse"
            geometry={nodes.Ellipse.geometry}
            material={materials['Ellipse Material']}
            castShadow
            receiveShadow
            position={[1.11, -4.32, -20]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          />
          <mesh
            name="Rectangle"
            geometry={nodes.Rectangle.geometry}
            material={materials['Rectangle Material']}
            castShadow
            receiveShadow
            position={[0.21, -1.5, 0]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          />
          <mesh
            name="Rectangle 2"
            geometry={nodes['Rectangle 2'].geometry}
            material={materials['House Borders']}
            castShadow
            receiveShadow
            position={[-1.11, 0, 0]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          />
        </group>
        <mesh
          name="Cylinder 2"
          geometry={nodes['Cylinder 2'].geometry}
          material={materials['Cylinder 2 Material']}
          castShadow
          receiveShadow
          position={[736.48, -129.71, 288.39]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          name="Cylinder 3"
          geometry={nodes['Cylinder 3'].geometry}
          material={materials['Cylinder 3 Material']}
          castShadow
          receiveShadow
          position={[295.43, -80.36, -637.8]}
          rotation={[-Math.PI, -1.2, -Math.PI / 2]}
          scale={1}
        />
        <mesh
          name="Cylinder"
          geometry={nodes.Cylinder.geometry}
          material={materials['Cylinder Material']}
          castShadow
          receiveShadow
          position={[684.65, -129.71, -333.12]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <group name="Birds" position={[795.24, 568.84, -368.8]}>
          <mesh
            name="Cube 7"
            geometry={nodes['Cube 7'].geometry}
            material={materials['Cube 7 Material']}
            castShadow
            receiveShadow
            position={[132.57, -100.64, 312.66]}
            rotation={[1.51, -0.32, 1.14]}
            scale={[0.69, 0.69, 0.49]}
          />
          <mesh
            name="Cube 8"
            geometry={nodes['Cube 8'].geometry}
            material={materials['Cube 8 Material']}
            castShadow
            receiveShadow
            position={[-37.6, -293.91, -301.11]}
            rotation={[0.98, -0.43, -0.19]}
            scale={[0.6, 0.6, 0.43]}
          />
          <mesh
            name="Cube 6"
            geometry={nodes['Cube 6'].geometry}
            material={materials['Cube 6 Material']}
            castShadow
            receiveShadow
            position={[136.08, 127.87, -225.51]}
            rotation={[2.14, -0.48, 0.49]}
            scale={[0.69, 0.69, 0.49]}
          />
          <mesh
            name="Cube 5"
            geometry={nodes['Cube 5'].geometry}
            material={materials['Cube 5 Material']}
            castShadow
            receiveShadow
            position={[80.34, 218.98, 15.99]}
            rotation={[1.43, 0.32, 0.17]}
            scale={[0.85, 0.85, 0.61]}
          />
          <mesh
            name="Cube 4"
            geometry={nodes['Cube 4'].geometry}
            material={materials['Cube 4 Material']}
            castShadow
            receiveShadow
            position={[-149.26, 270.7, -51.29]}
            rotation={[0.62, 0.54, -0.35]}
            scale={[0.93, 0.93, 0.66]}
          />
        </group>
        <mesh
          name="Cloud"
          geometry={nodes.Cloud.geometry}
          material={materials['Clouds B']}
          castShadow
          receiveShadow
          position={[547.51, 720.1, -1321.1]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={1}
        />
        <mesh
          name="Cloud1"
          geometry={nodes.Cloud1.geometry}
          material={materials['Clouds B']}
          castShadow
          receiveShadow
          position={[277.41, 501.97, -1392.69]}
          rotation={[-Math.PI / 2, 0, -1.74]}
          scale={1}
        />
        <mesh
          name="Cloud2"
          geometry={nodes.Cloud2.geometry}
          material={materials['Clouds A']}
          castShadow
          receiveShadow
          position={[1056.26, 666.48, 578.77]}
          rotation={[0.38, 0.31, -0.12]}
          scale={1}
        />
        <mesh name="Cloud3" geometry={nodes.Cloud3.geometry} material={materials['Clouds A']} castShadow receiveShadow position={[1596.85, 677.1, -529.76]} />
        <mesh name="Cloud4" geometry={nodes.Cloud4.geometry} material={materials['Clouds A']} castShadow receiveShadow position={[1216.09, 815.7, -579.92]} />
        <group name="Steps1" position={[-18, 25.76, 58]} rotation={[0, 0, 0]}>
          <mesh
            name="Cube"
            geometry={nodes.Cube.geometry}
            material={materials.LampPosts}
            castShadow
            receiveShadow
            position={[770.95, -57.01, 481.96]}
            rotation={[0, Math.PI / 3, -Math.PI / 2]}
            scale={1}
          />
          <mesh
            name="Cube1"
            geometry={nodes.Cube1.geometry}
            material={materials.LampPosts}
            castShadow
            receiveShadow
            position={[800.25, -57.01, -425.17]}
            rotation={[-Math.PI, Math.PI / 3, Math.PI / 2]}
            scale={1}
          />
          <mesh
            name="Cube2"
            geometry={nodes.Cube2.geometry}
            material={materials.LampPosts}
            castShadow
            receiveShadow
            position={[31.91, -57.01, -905.42]}
            rotation={[-Math.PI, 0, Math.PI / 2]}
            scale={1}
          />
          <mesh
            name="Cube3"
            geometry={nodes.Cube3.geometry}
            material={materials.LampPosts}
            castShadow
            receiveShadow
            position={[-756.28, -57.01, -473.49]}
            rotation={[-Math.PI, -Math.PI / 3, Math.PI / 2]}
            scale={1}
          />
          <mesh
            name="Cube4"
            geometry={nodes.Cube4.geometry}
            material={materials.LampPosts}
            castShadow
            receiveShadow
            position={[-788.19, -57.01, 418.21]}
            rotation={[0, -Math.PI / 3, -Math.PI / 2]}
            scale={1}
          />
          <mesh
            name="Cube5"
            geometry={nodes.Cube5.geometry}
            material={materials.LampPosts}
            castShadow
            receiveShadow
            position={[-31.91, -57.01, 896.78]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={1}
          />
        </group>
        <mesh
          name="Plane"
          geometry={nodes.Plane.geometry}
          material={materials.Pathway}
          castShadow
          receiveShadow
          position={[284.06, 15.34, 338]}
          rotation={[-0.94, 0.14, -1.58]}
          scale={1}
        />
        <group name="Fence" position={[96.16, 232.05, 62.57]}>
          <mesh
            name="Rectangle 20"
            geometry={nodes['Rectangle 20'].geometry}
            material={materials['House Wood Fence']}
            castShadow
            receiveShadow
            position={[261.96, 55.64, -152.21]}
            rotation={[0, 1.5, -Math.PI / 2]}
            scale={0.78}
          />
          <mesh
            name="Rectangle 19"
            geometry={nodes['Rectangle 19'].geometry}
            material={materials['House Wood Fence']}
            castShadow
            receiveShadow
            position={[257.74, 49.96, -126.16]}
            rotation={[0.05, 1.24, -1.56]}
            scale={0.73}
          />
          <mesh
            name="Rectangle 18"
            geometry={nodes['Rectangle 18'].geometry}
            material={materials['House Wood Fence']}
            castShadow
            receiveShadow
            position={[246.65, 42.12, -99.06]}
            rotation={[0, 1.15, -Math.PI / 2]}
            scale={0.94}
          />
          <mesh
            name="Rectangle 17"
            geometry={nodes['Rectangle 17'].geometry}
            material={materials['House Wood Fence']}
            castShadow
            receiveShadow
            position={[231.89, 32.63, -75.34]}
            rotation={[-0.1, 0.71, -1.58]}
            scale={0.83}
          />
          <mesh
            name="Rectangle 16"
            geometry={nodes['Rectangle 16'].geometry}
            material={materials['House Wood Fence']}
            castShadow
            receiveShadow
            position={[197.61, -37.76, 71.88]}
            rotation={[0, 0.89, -1.55]}
            scale={1}
          />
          <mesh
            name="Rectangle 15"
            geometry={nodes['Rectangle 15'].geometry}
            material={materials['House Wood Fence']}
            castShadow
            receiveShadow
            position={[178.5, -45.02, 98.08]}
            rotation={[-0.14, 0.89, -1.53]}
            scale={0.92}
          />
          <mesh
            name="Rectangle 14"
            geometry={nodes['Rectangle 14'].geometry}
            material={materials['House Wood Fence']}
            castShadow
            receiveShadow
            position={[153.89, -53.99, 125.09]}
            rotation={[0, 0.8, -1.64]}
            scale={1}
          />
          <mesh
            name="Rectangle 13"
            geometry={nodes['Rectangle 13'].geometry}
            material={materials['House Wood Fence']}
            castShadow
            receiveShadow
            position={[128.2, -53.99, 144.81]}
            rotation={[0, 0.54, -1.49]}
            scale={[1, 0.84, 1]}
          />
          <mesh
            name="Rectangle 12"
            geometry={nodes['Rectangle 12'].geometry}
            material={materials['House Wood Fence']}
            castShadow
            receiveShadow
            position={[98.25, -47.85, 150.34]}
            rotation={[0, -0.07, -Math.PI / 2]}
            scale={1}
          />
          <mesh
            name="Rectangle 11"
            geometry={nodes['Rectangle 11'].geometry}
            material={materials['House Wood Fence']}
            castShadow
            receiveShadow
            position={[66.05, -41.76, 148.05]}
            rotation={[0, -0.07, -1.66]}
            scale={0.91}
          />
          <mesh
            name="Rectangle 10"
            geometry={nodes['Rectangle 10'].geometry}
            material={materials['House Wood Fence']}
            castShadow
            receiveShadow
            position={[33.83, -39.34, 145.76]}
            rotation={[0, -0.07, -1.61]}
            scale={[1, 0.79, 1]}
          />
          <mesh
            name="Rectangle 9"
            geometry={nodes['Rectangle 9'].geometry}
            material={materials['House Wood Fence']}
            castShadow
            receiveShadow
            position={[0.57, -32.45, 143.39]}
            rotation={[0, -0.07, -1.68]}
            scale={1.06}
          />
          <mesh
            name="Rectangle 8"
            geometry={nodes['Rectangle 8'].geometry}
            material={materials['House Wood Fence']}
            castShadow
            receiveShadow
            position={[-38.18, -27.89, 140.64]}
            rotation={[0, -0.07, -Math.PI / 2]}
            scale={0.9}
          />
          <mesh
            name="Rectangle 7"
            geometry={nodes['Rectangle 7'].geometry}
            material={materials['House Wood Fence']}
            castShadow
            receiveShadow
            position={[-71.99, -24.86, 138.23]}
            rotation={[0, -0.07, -1.52]}
            scale={1}
          />
          <mesh
            name="Rectangle 6"
            geometry={nodes['Rectangle 6'].geometry}
            material={materials['House Wood Fence']}
            castShadow
            receiveShadow
            position={[-101.92, -21.48, 136.11]}
            rotation={[0, -0.07, -Math.PI / 2]}
            scale={[1, 0.84, 1]}
          />
          <mesh
            name="Rectangle 5"
            geometry={nodes['Rectangle 5'].geometry}
            material={materials['House Wood Fence']}
            castShadow
            receiveShadow
            position={[-138.01, -21.48, 133.54]}
            rotation={[0, -0.07, -1.65]}
            scale={1.08}
          />
          <mesh
            name="Rectangle 4"
            geometry={nodes['Rectangle 4'].geometry}
            material={materials['House Wood Fence']}
            castShadow
            receiveShadow
            position={[-171.25, -21.48, 131.18]}
            rotation={[0, -0.07, -1.47]}
            scale={0.89}
          />
          <mesh
            name="Rectangle 31"
            geometry={nodes['Rectangle 31'].geometry}
            material={materials['House Wood Fence']}
            castShadow
            receiveShadow
            position={[-201.59, -21.48, 129.02]}
            rotation={[0, -0.07, -Math.PI / 2]}
            scale={0.93}
          />
          <mesh
            name="Rectangle 21"
            geometry={nodes['Rectangle 21'].geometry}
            material={materials['House Wood Fence']}
            castShadow
            receiveShadow
            position={[-231.57, -21.48, 123.43]}
            rotation={[0, -0.26, -Math.PI / 2]}
            scale={[0.93, 0.74, 0.93]}
          />
          <mesh
            name="Rectangle1"
            geometry={nodes.Rectangle1.geometry}
            material={materials['House Wood Fence']}
            castShadow
            receiveShadow
            position={[-256.18, -21.48, 108.96]}
            rotation={[0, -0.7, -Math.PI / 2]}
            scale={0.93}
          />
        </group>
        <group name="House" position={[65.54, 391.65, -64.6]}>
          <mesh
            name="Cube 43"
            geometry={nodes['Cube 43'].geometry}
            material={materials['House Ceiling']}
            castShadow
            receiveShadow
            position={[-17.54, 88.32, -6.4]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Cube 42"
            geometry={nodes['Cube 42'].geometry}
            material={materials['House Borders']}
            castShadow
            receiveShadow
            position={[-17.54, 76.98, -6.4]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Cube 40"
            geometry={nodes['Cube 40'].geometry}
            material={materials['House Borders']}
            castShadow
            receiveShadow
            position={[-90.54, -100.6, -145.86]}
            rotation={[-Math.PI, 0, -Math.PI / 2]}
            scale={[1, 1, 0.4]}
          />
          <mesh
            name="Cube 39"
            geometry={nodes['Cube 39'].geometry}
            material={materials['House Borders']}
            castShadow
            receiveShadow
            position={[-90.54, -10.49, -145.86]}
            rotation={[-Math.PI, 0, -Math.PI / 2]}
            scale={[1, 1, 0.4]}
          />
          <mesh
            name="Cube 23"
            geometry={nodes['Cube 23'].geometry}
            material={materials['House Walls']}
            castShadow
            receiveShadow
            position={[-175.78, -122.01, 67.15]}
          />
          <mesh
            name="Cube 20"
            geometry={nodes['Cube 20'].geometry}
            material={materials['House Borders']}
            castShadow
            receiveShadow
            position={[-78.09, -87.06, 132.61]}
          />
          <mesh
            name="Cube 81"
            geometry={nodes['Cube 81'].geometry}
            material={materials['House Windows']}
            castShadow
            receiveShadow
            position={[-78.09, -87.06, 135.54]}
          />
          <mesh
            name="Cube 131"
            geometry={nodes['Cube 131'].geometry}
            material={materials['House Ceiling']}
            castShadow
            receiveShadow
            position={[54.43, -46.53, 170.07]}
            scale={[1, 1, 1.71]}
          />
          <mesh
            name="Cube 16"
            geometry={nodes['Cube 16'].geometry}
            material={materials['House Borders']}
            castShadow
            receiveShadow
            position={[92.97, -92.59, 160.77]}
          />
          <mesh
            name="Cube 151"
            geometry={nodes['Cube 151'].geometry}
            material={materials['House Borders']}
            castShadow
            receiveShadow
            position={[15.35, -92.01, 160.77]}
          />
          <mesh
            name="Cube 161"
            geometry={nodes['Cube 161'].geometry}
            material={materials['House Borders']}
            castShadow
            receiveShadow
            position={[92.97, -92.59, 177.11]}
          />
          <mesh
            name="Cube 18"
            geometry={nodes['Cube 18'].geometry}
            material={materials['House Borders']}
            castShadow
            receiveShadow
            position={[53.67, -92.01, 177.11]}
          />
          <mesh
            name="Cube 29"
            geometry={nodes['Cube 29'].geometry}
            material={materials['Concrete/Stones']}
            castShadow
            receiveShadow
            position={[-166.8, -66.05, 21.98]}
          />
          <mesh
            name="Cube 30"
            geometry={nodes['Cube 30'].geometry}
            material={materials['House Borders']}
            castShadow
            receiveShadow
            position={[-198.14, -66.05, 67.21]}
          />
          <mesh
            name="Cube 28"
            geometry={nodes['Cube 28'].geometry}
            material={materials['House Borders']}
            castShadow
            receiveShadow
            position={[-198.14, -66.05, 21.98]}
          />
          <mesh
            name="Cube 27"
            geometry={nodes['Cube 27'].geometry}
            material={materials['House Borders']}
            castShadow
            receiveShadow
            position={[-198.14, -66.05, 114.37]}
          />
          <mesh
            name="Cube 141"
            geometry={nodes['Cube 141'].geometry}
            material={materials['House Borders']}
            castShadow
            receiveShadow
            position={[15.35, -92.01, 177.11]}
          />
          <mesh
            name="Cube 17"
            geometry={nodes['Cube 17'].geometry}
            material={materials['House Borders']}
            castShadow
            receiveShadow
            position={[54.43, -131.66, 170.07]}
            scale={[1, 1, 1.71]}
          />
          <mesh
            name="Cube 121"
            geometry={nodes['Cube 121'].geometry}
            material={materials['House Borders']}
            castShadow
            receiveShadow
            position={[54.43, -52.63, 170.07]}
            scale={[1, 1, 1.71]}
          />
          <mesh
            name="Cube 111"
            geometry={nodes['Cube 111'].geometry}
            material={materials['House Windows']}
            castShadow
            receiveShadow
            position={[54.3, -92, 167.6]}
            scale={[1, 1, 1.71]}
          />
          <mesh
            name="Cube 19"
            geometry={nodes['Cube 19'].geometry}
            material={materials['House Borders']}
            castShadow
            receiveShadow
            position={[54.3, 30.01, 160.86]}
          />
          <mesh
            name="Cube 101"
            geometry={nodes['Cube 101'].geometry}
            material={materials['House Windows']}
            castShadow
            receiveShadow
            position={[54.3, 30.01, 162.86]}
          />
          <mesh
            name="Cube 41"
            geometry={nodes['Cube 41'].geometry}
            material={materials['Concrete/Stones']}
            castShadow
            receiveShadow
            position={[-167.14, 41.97, -95.83]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={0.42}
          />
          <mesh
            name="Cube 22"
            geometry={nodes['Cube 22'].geometry}
            material={materials['House Borders']}
            castShadow
            receiveShadow
            position={[-166.93, 20.24, 61.54]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={0.76}
          />
          <mesh
            name="Cube 38"
            geometry={nodes['Cube 38'].geometry}
            material={materials['House Borders']}
            castShadow
            receiveShadow
            position={[-90.97, -60.95, -140.66]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={0.89}
          />
          <mesh
            name="Cube 37"
            geometry={nodes['Cube 37'].geometry}
            material={materials['House Borders']}
            castShadow
            receiveShadow
            position={[-90.97, 28.26, -140.66]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={0.89}
          />
          <mesh
            name="Cube 36"
            geometry={nodes['Cube 36'].geometry}
            material={materials['House Borders']}
            castShadow
            receiveShadow
            position={[51.09, 28.26, -180.94]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={0.76}
          />
          <mesh
            name="Cube 35"
            geometry={nodes['Cube 35'].geometry}
            material={materials['House Borders']}
            castShadow
            receiveShadow
            position={[132.9, 30.01, -74.45]}
            rotation={[0, Math.PI / 2, 0]}
            scale={0.66}
          />
          <mesh
            name="Cube 31"
            geometry={nodes['Cube 31'].geometry}
            material={materials['House Borders']}
            castShadow
            receiveShadow
            position={[132.69, 30.01, 52.57]}
            rotation={[0, Math.PI / 2, 0]}
          />
          <mesh
            name="Cube 21"
            geometry={nodes['Cube 21'].geometry}
            material={materials['House Borders']}
            castShadow
            receiveShadow
            position={[-78.09, 30.01, 131.07]}
          />
          <mesh
            name="Cube 24"
            geometry={nodes['Cube 24'].geometry}
            material={materials['House Windows']}
            castShadow
            receiveShadow
            position={[-177.79, -66.12, 68.03]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={0.76}
          />
          <mesh
            name="Cube 411"
            geometry={nodes['Cube 411'].geometry}
            material={materials['House Windows']}
            castShadow
            receiveShadow
            position={[-167.86, 41.97, -95.83]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={0.42}
          />
          <mesh
            name="Cube 221"
            geometry={nodes['Cube 221'].geometry}
            material={materials['House Windows']}
            castShadow
            receiveShadow
            position={[-168.24, 20.24, 61.54]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={0.76}
          />
          <mesh
            name="Cube 381"
            geometry={nodes['Cube 381'].geometry}
            material={materials['House Windows']}
            castShadow
            receiveShadow
            position={[-90.97, -60.95, -142.2]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={0.89}
          />
          <mesh
            name="Cube 371"
            geometry={nodes['Cube 371'].geometry}
            material={materials['House Windows']}
            castShadow
            receiveShadow
            position={[-90.97, 28.26, -142.2]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={0.89}
          />
          <mesh
            name="Cube 361"
            geometry={nodes['Cube 361'].geometry}
            material={materials['House Windows']}
            castShadow
            receiveShadow
            position={[51.09, 28.26, -182.25]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={0.76}
          />
          <mesh
            name="Cube 351"
            geometry={nodes['Cube 351'].geometry}
            material={materials['House Windows']}
            castShadow
            receiveShadow
            position={[134.03, 30.01, -74.45]}
            rotation={[0, Math.PI / 2, 0]}
            scale={0.66}
          />
          <mesh
            name="Cube 311"
            geometry={nodes['Cube 311'].geometry}
            material={materials['House Windows']}
            castShadow
            receiveShadow
            position={[134.41, 30.01, 52.57]}
            rotation={[0, Math.PI / 2, 0]}
          />
          <mesh
            name="Cube 71"
            geometry={nodes['Cube 71'].geometry}
            material={materials['House Windows']}
            castShadow
            receiveShadow
            position={[-78.09, 30.01, 132.8]}
          />
          <mesh
            name="Cube 91"
            geometry={nodes['Cube 91'].geometry}
            material={materials['House Ceiling']}
            castShadow
            receiveShadow
            position={[-189.87, 6, -95.22]}
            rotation={[-Math.PI / 2, -0.48, Math.PI]}
            scale={1}
          />
          <mesh
            name="Cube 61"
            geometry={nodes['Cube 61'].geometry}
            material={materials['House Ceiling']}
            castShadow
            receiveShadow
            position={[-163.6, -43.44, 156.79]}
            rotation={[-1.09, 0, -Math.PI / 2]}
            scale={1}
          />
          <mesh
            name="Cube 92"
            geometry={nodes['Cube 92'].geometry}
            material={materials['House Borders']}
            castShadow
            receiveShadow
            position={[-186.75, 0.02, -95.22]}
            rotation={[-Math.PI / 2, -0.48, Math.PI]}
            scale={1}
          />
          <mesh
            name="Cube 26"
            geometry={nodes['Cube 26'].geometry}
            material={materials['House Ceiling']}
            castShadow
            receiveShadow
            position={[-180.28, -29.4, 75.8]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Cube 25"
            geometry={nodes['Cube 25'].geometry}
            material={materials['House Borders']}
            castShadow
            receiveShadow
            position={[-180.28, -35.6, 74.3]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Cube 51"
            geometry={nodes['Cube 51'].geometry}
            material={materials['House Borders']}
            castShadow
            receiveShadow
            position={[-163.6, -49.39, 153.69]}
            rotation={[-1.09, 0, -Math.PI / 2]}
            scale={1}
          />
          <mesh
            name="Cube 93"
            geometry={nodes['Cube 93'].geometry}
            material={materials['House Walls']}
            castShadow
            receiveShadow
            position={[-174.97, -62.98, -95.4]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={1}
          />
          <mesh
            name="Cube 44"
            geometry={nodes['Cube 44'].geometry}
            material={materials['House Walls']}
            castShadow
            receiveShadow
            position={[-163.79, -112.59, 142.21]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Cube 312"
            geometry={nodes['Cube 312'].geometry}
            material={materials['House Walls']}
            castShadow
            receiveShadow
            position={[143.83, -9.56, 53.44]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            scale={1}
          />
          <mesh
            name="Cube 3"
            geometry={nodes['Cube 3'].geometry}
            material={materials['House Walls']}
            castShadow
            receiveShadow
            position={[-78.96, -9.56, 142.21]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Cube 34"
            geometry={nodes['Cube 34'].geometry}
            material={materials['House Ceiling']}
            castShadow
            receiveShadow
            position={[167.04, -26.25, -71.25]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            scale={1}
          />
          <mesh
            name="Cube 33"
            geometry={nodes['Cube 33'].geometry}
            material={materials['Concrete/Stones']}
            castShadow
            receiveShadow
            position={[167.04, -30.4, -71.25]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            scale={1}
          />
          <mesh
            name="Cube 32"
            geometry={nodes['Cube 32'].geometry}
            material={materials['House Walls']}
            castShadow
            receiveShadow
            position={[167.04, -84.57, -71.25]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            scale={1}
          />
          <mesh
            name="Cube 2"
            geometry={nodes['Cube 2'].geometry}
            material={materials['House Walls']}
            castShadow
            receiveShadow
            position={[50.31, -57.07, -10.72]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Cube6"
            geometry={nodes.Cube6.geometry}
            material={materials['House Walls']}
            castShadow
            receiveShadow
            position={[-17.4, -45.07, -4.57]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
        </group>
        <group name="Stones" position={[-186.78, -36, -70.79]}>
          <mesh
            name="Icosahedron 4"
            geometry={nodes['Icosahedron 4'].geometry}
            material={materials['Concrete/Stones']}
            castShadow
            receiveShadow
            position={[599.92, 346.06, -51.86]}
            rotation={[-2.31, 0.9, -0.17]}
            scale={0.76}
          />
          <mesh
            name="Icosahedron 3"
            geometry={nodes['Icosahedron 3'].geometry}
            material={materials['Concrete/Stones']}
            castShadow
            receiveShadow
            position={[-285.34, -52.36, 1044.1]}
            rotation={[-2.53, 0.64, 0.15]}
            scale={1}
          />
          <mesh
            name="Icosahedron 2"
            geometry={nodes['Icosahedron 2'].geometry}
            material={materials['Concrete/Stones']}
            castShadow
            receiveShadow
            position={[304.41, -198.21, -782.78]}
            rotation={[-2.53, 0.64, 0.15]}
            scale={1.92}
          />
          <mesh
            name="Icosahedron"
            geometry={nodes.Icosahedron.geometry}
            material={materials['Concrete/Stones']}
            castShadow
            receiveShadow
            position={[-423.87, -105.57, -898.95]}
            rotation={[-2.44, 0.02, 0.49]}
            scale={1}
          />
          <mesh
            name="Cube 45"
            geometry={nodes['Cube 45'].geometry}
            material={materials['Concrete/Stones']}
            castShadow
            receiveShadow
            position={[-1018.37, -131.14, -717.89]}
            rotation={[-1.54, -0.41, 0.29]}
            scale={1}
          />
          <mesh
            name="Cube 152"
            geometry={nodes['Cube 152'].geometry}
            material={materials['Concrete/Stones']}
            castShadow
            receiveShadow
            position={[1229.77, -100.57, 498.2]}
            rotation={[-0.88, 0.49, -0.58]}
            scale={1}
          />
          <mesh
            name="Cube 210"
            geometry={nodes['Cube 210'].geometry}
            material={materials['Concrete/Stones']}
            castShadow
            receiveShadow
            position={[-203.15, -25.28, -783.44]}
            rotation={[-0.88, 0.49, -0.01]}
            scale={1}
          />
          <mesh
            name="Cube 222"
            geometry={nodes['Cube 222'].geometry}
            material={materials['Concrete/Stones']}
            castShadow
            receiveShadow
            position={[-86.08, 231.88, 178.99]}
            rotation={[-1.56, -1.43, 0.06]}
            scale={[-1, 1, 3.19]}
          />
          <mesh
            name="Cube 211"
            geometry={nodes['Cube 211'].geometry}
            material={materials['Concrete/Stones']}
            castShadow
            receiveShadow
            position={[301.9, 291.28, -353.44]}
            rotation={[-0.4, 0.19, -2.01]}
            scale={[1, 1, 1.17]}
          />
          <mesh
            name="Cube 231"
            geometry={nodes['Cube 231'].geometry}
            material={materials['Concrete/Stones']}
            castShadow
            receiveShadow
            position={[-17.57, 2.82, 684.29]}
            rotation={[-0.59, -0.34, 1.54]}
            scale={[1, 1, 1.17]}
          />
          <mesh
            name="Cube 201"
            geometry={nodes['Cube 201'].geometry}
            material={materials['Concrete/Stones']}
            castShadow
            receiveShadow
            position={[-98.21, -49.67, 1082.08]}
            rotation={[-0.63, -0.38, -2.35]}
            scale={[1, 1, 1.17]}
          />
          <mesh
            name="Cube 310"
            geometry={nodes['Cube 310'].geometry}
            material={materials['Concrete/Stones']}
            castShadow
            receiveShadow
            position={[662.83, -193.05, -710.04]}
            rotation={[-0.63, -0.38, -2.35]}
            scale={[1.92, 1.92, 2.25]}
          />
          <mesh
            name="Cube7"
            geometry={nodes.Cube7.geometry}
            material={materials['Concrete/Stones']}
            castShadow
            receiveShadow
            position={[-502.08, -121.33, -703.03]}
            rotation={[-2.21, -0.45, 1.23]}
            scale={[1, 1, 1.17]}
          />
        </group>
        <group name="Trees 1" position={[-511.47, 190.72, 464.53]} rotation={[1.55, -1.33, 1.2]} scale={1}>
          <mesh
            name="Cube 212"
            geometry={nodes['Cube 212'].geometry}
            material={materials['Trees A']}
            castShadow
            receiveShadow
            position={[135.17, -56, 13.61]}
            rotation={[-1.57, 0.06, -2.32]}
            scale={0.78}
          />
          <mesh
            name="Cube8"
            geometry={nodes.Cube8.geometry}
            material={materials['Trees B']}
            castShadow
            receiveShadow
            position={[-19.75, 51.57, 96.35]}
            rotation={[-1.57, -0.07, -3.09]}
            scale={1.09}
          />
          <mesh
            name="Cylinder1"
            geometry={nodes.Cylinder1.geometry}
            material={materials['Cylinder1 Material']}
            castShadow
            receiveShadow
            position={[28.92, -154.53, 59.86]}
            rotation={[0, -Math.PI / 2, 0]}
          />
        </group>
        <group name="Tress 2" position={[-751.9, 178.66, -469.61]} rotation={[-0.32, -0.72, -0.47]} scale={1}>
          <mesh
            name="Cube 46"
            geometry={nodes['Cube 46'].geometry}
            material={materials['Trees A']}
            castShadow
            receiveShadow
            position={[-88.94, -26.88, -87.25]}
            rotation={[-1.57, 0.06, -2.32]}
            scale={1}
          />
          <mesh
            name="Cube9"
            geometry={nodes.Cube9.geometry}
            material={materials['Trees A']}
            castShadow
            receiveShadow
            position={[-28.36, 71, 100.8]}
            rotation={[-1.57, -0.07, -3.09]}
            scale={[1.09, 1.09, 0.94]}
          />
          <mesh
            name="Cylinder2"
            geometry={nodes.Cylinder2.geometry}
            material={materials['Cylinder2 Material']}
            castShadow
            receiveShadow
            position={[28.92, -154.53, 59.86]}
            rotation={[0, -Math.PI / 2, 0]}
          />
        </group>
        <group name="Bush" position={[64.86, 252.16, -9.63]}>
          <mesh
            name="Cube 112"
            geometry={nodes['Cube 112'].geometry}
            material={materials['Trees A']}
            castShadow
            receiveShadow
            position={[-264.11, 60.73, -131.45]}
            rotation={[-1.02, -0.28, -0.61]}
            scale={[0.94, 0.94, 1.19]}
          />
          <mesh
            name="Cube 102"
            geometry={nodes['Cube 102'].geometry}
            material={materials['Trees A']}
            castShadow
            receiveShadow
            position={[-318.15, -16.38, 94.75]}
            rotation={[-1.02, -0.28, -0.61]}
            scale={[0.94, 0.94, 1.19]}
          />
          <mesh
            name="Cube 94"
            geometry={nodes['Cube 94'].geometry}
            material={materials['Trees B']}
            castShadow
            receiveShadow
            position={[-249.49, -28.63, 166.34]}
            rotation={[-0.61, -0.01, -0.97]}
            scale={[0.94, 0.94, 1.19]}
          />
          <mesh
            name="Cube 122"
            geometry={nodes['Cube 122'].geometry}
            material={materials['Cube 122 Material']}
            castShadow
            receiveShadow
            position={[-316.45, -283.16, 538.56]}
            rotation={[-2.38, 0.59, 1.69]}
            scale={0.94}
          />
          <mesh
            name="Cube 82"
            geometry={nodes['Cube 82'].geometry}
            material={materials['Cube 82 Material']}
            castShadow
            receiveShadow
            position={[8.47, -71.25, 241.42]}
            rotation={[-0.61, -0.01, -0.97]}
            scale={0.94}
          />
          <mesh
            name="Cube 123"
            geometry={nodes['Cube 123'].geometry}
            material={materials['Trees A']}
            castShadow
            receiveShadow
            position={[-393.92, -273.16, 501.42]}
            rotation={[-2.34, 0.28, 1.67]}
            scale={0.94}
          />
          <mesh
            name="Cube 72"
            geometry={nodes['Cube 72'].geometry}
            material={materials['Trees A']}
            castShadow
            receiveShadow
            position={[90.91, -61.25, 217.26]}
            rotation={[-0.79, 0.25, -0.95]}
            scale={0.94}
          />
          <mesh
            name="Cube 62"
            geometry={nodes['Cube 62'].geometry}
            material={materials['Trees A']}
            castShadow
            receiveShadow
            position={[310.67, 78.17, -177.34]}
            rotation={[-1.52, -0.24, -1.08]}
            scale={0.94}
          />
        </group>
        <group name="Trees 3" position={[-146.75, 391.37, -326.32]} rotation={[-0.13, -0.02, -0.05]} scale={1.2}>
          <mesh
            name="Cube 47"
            geometry={nodes['Cube 47'].geometry}
            material={materials['Trees A']}
            castShadow
            receiveShadow
            position={[-216.3, -10.8, 24.11]}
            rotation={[-1.49, -0.38, -2.85]}
            scale={1}
          />
          <mesh
            name="Cube 52"
            geometry={nodes['Cube 52'].geometry}
            material={materials['Trees A']}
            castShadow
            receiveShadow
            position={[-136.23, -44.36, 153.85]}
            rotation={[-1.38, -0.29, -1.05]}
            scale={0.78}
          />
          <mesh
            name="Cube 213"
            geometry={nodes['Cube 213'].geometry}
            material={materials['Trees A']}
            castShadow
            receiveShadow
            position={[-32.45, 31.48, -141.5]}
            rotation={[-1.26, 0.03, 1.05]}
            scale={0.78}
          />
          <mesh
            name="Cube10"
            geometry={nodes.Cube10.geometry}
            material={materials['Cube10 Material']}
            castShadow
            receiveShadow
            position={[-77.97, 107.89, 85.7]}
            rotation={[-1.77, 0.13, 2.98]}
            scale={1.29}
          />
          <mesh
            name="Cylinder3"
            geometry={nodes.Cylinder3.geometry}
            material={materials['Cylinder3 Material']}
            castShadow
            receiveShadow
            position={[-58.55, -79.71, 59.86]}
            rotation={[Math.PI / 2, -1.28, Math.PI / 2]}
            scale={1}
          />
        </group>
        <group name="Trees 4" position={[-554.89, 191.91, -4.7]} rotation={[-0.13, -0.02, -0.05]} scale={1.2}>
          <mesh
            name="Cube 48"
            geometry={nodes['Cube 48'].geometry}
            material={materials['Trees A']}
            castShadow
            receiveShadow
            position={[-212.31, -20.9, 23.28]}
            rotation={[-1.49, -0.38, -2.85]}
            scale={1}
          />
          <mesh
            name="Cube 53"
            geometry={nodes['Cube 53'].geometry}
            material={materials['Trees A']}
            castShadow
            receiveShadow
            position={[-145.42, -48.09, 158.72]}
            rotation={[-1.38, -0.29, -1.05]}
            scale={0.78}
          />
          <mesh
            name="Cube 214"
            geometry={nodes['Cube 214'].geometry}
            material={materials['Trees A']}
            castShadow
            receiveShadow
            position={[-32.45, 31.48, -141.5]}
            rotation={[-1.26, 0.03, 1.05]}
            scale={0.78}
          />
          <mesh
            name="Cube11"
            geometry={nodes.Cube11.geometry}
            material={materials['Cube11 Material']}
            castShadow
            receiveShadow
            position={[-39.21, 106.59, 92.22]}
            rotation={[-1.76, 0.19, 2.98]}
            scale={1.29}
          />
          <mesh
            name="Cylinder4"
            geometry={nodes.Cylinder4.geometry}
            material={materials['Cylinder4 Material']}
            castShadow
            receiveShadow
            position={[-52.01, -101.81, 59.86]}
            rotation={[Math.PI / 2, -1.28, Math.PI / 2]}
            scale={1}
          />
        </group>
        <group name="Trees 5" position={[-1197.33, 163.59, -336.67]} rotation={[-0.86, 1.46, 0.93]} scale={0.86}>
          <mesh
            name="Cube 49"
            geometry={nodes['Cube 49'].geometry}
            material={materials['Trees A']}
            castShadow
            receiveShadow
            position={[-286.81, -88.04, 100.05]}
            rotation={[-1.49, -0.38, -1.6]}
            scale={1}
          />
          <mesh
            name="Cube 215"
            geometry={nodes['Cube 215'].geometry}
            material={materials['Trees A']}
            castShadow
            receiveShadow
            position={[205.21, -128.14, 20.14]}
            rotation={[-1.35, 0.69, -0.58]}
            scale={0.78}
          />
          <mesh
            name="Cube12"
            geometry={nodes.Cube12.geometry}
            material={materials['Cube12 Material']}
            castShadow
            receiveShadow
            position={[-58.92, 117.88, 2.86]}
            rotation={[-1.57, -0.07, -3.09]}
            scale={1.29}
          />
          <mesh
            name="Cylinder5"
            geometry={nodes.Cylinder5.geometry}
            material={materials['Cylinder5 Material']}
            castShadow
            receiveShadow
            position={[-37.2, -151.9, 59.86]}
            rotation={[Math.PI / 2, -1.28, Math.PI / 2]}
            scale={1}
          />
        </group>
        <group name="Trees 6" position={[-1037.83, 335.19, -731]} rotation={[-0.11, 0.33, -0.06]} scale={1.2}>
          <mesh
            name="Cube 410"
            geometry={nodes['Cube 410'].geometry}
            material={materials['Trees A']}
            castShadow
            receiveShadow
            position={[-187.69, -35.33, -58.96]}
            rotation={[-1.49, -0.38, -2.26]}
            scale={1}
          />
          <mesh
            name="Cube 54"
            geometry={nodes['Cube 54'].geometry}
            material={materials['Trees A']}
            castShadow
            receiveShadow
            position={[45.97, -108.45, 34.72]}
            rotation={[-1.57, 0.06, -1.07]}
            scale={0.78}
          />
          <mesh
            name="Cube 216"
            geometry={nodes['Cube 216'].geometry}
            material={materials['Trees A']}
            castShadow
            receiveShadow
            position={[51.79, -39.46, -104.06]}
            rotation={[-1.11, 0.29, -0.88]}
            scale={0.78}
          />
          <mesh
            name="Cube13"
            geometry={nodes.Cube13.geometry}
            material={materials['Cube13 Material']}
            castShadow
            receiveShadow
            position={[-40.37, 65.54, 69.09]}
            rotation={[-1.57, -0.07, -3.09]}
            scale={1.29}
          />
          <mesh
            name="Cylinder6"
            geometry={nodes.Cylinder6.geometry}
            material={materials['Cylinder6 Material']}
            castShadow
            receiveShadow
            position={[-37.2, -151.9, 59.86]}
            rotation={[Math.PI / 2, -1.28, Math.PI / 2]}
            scale={1}
          />
        </group>
        <mesh
          name="Train"
          geometry={nodes.Train.geometry}
          material={materials['Train Material']}
          castShadow
          receiveShadow
          position={[-13.92, 58.45, 49.46]}
          rotation={[-Math.PI / 2, 0, 2.27]}
          scale={1}
        >
          <group name="Group 7" position={[-573.5, -277.6, -69.59]} rotation={[Math.PI / 2, Math.PI / 6, 0]} scale={1}>
            <mesh
              name="Cube 412"
              geometry={nodes['Cube 412'].geometry}
              material={materials['Train Windows']}
              castShadow
              receiveShadow
              position={[-170.56, 12.78, -128.52]}
              rotation={[0, 0, 0]}
            />
            <mesh
              name="Cube 313"
              geometry={nodes['Cube 313'].geometry}
              material={materials['Train Windows']}
              castShadow
              receiveShadow
              position={[-170.56, 12.78, 128.12]}
              rotation={[0, 0, 0]}
            />
            <group name="Group 5" position={[-222.31, 14.49, 8.35]} rotation={[0, 0, 0]} scale={[1, 1, 0.97]}>
              <mesh
                name="Cube 95"
                geometry={nodes['Cube 95'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[-2.78, 0, -79.3]}
                rotation={[-Math.PI / 2, 1.57, 0]}
                scale={[1, 0.85, 0.14]}
              />
              <mesh
                name="Cube 73"
                geometry={nodes['Cube 73'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[-2.78, 0, 105.01]}
                rotation={[-Math.PI / 2, 1.57, 0]}
                scale={[1, 0.85, 0.14]}
              />
              <mesh
                name="Cube 162"
                geometry={nodes['Cube 162'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[-0.69, 0, 78.22]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[1, 0.82, 0.14]}
              />
              <mesh
                name="Cube 153"
                geometry={nodes['Cube 153'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[-0.69, 0, 52.22]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[1, 0.82, 0.14]}
              />
              <mesh
                name="Cube 142"
                geometry={nodes['Cube 142'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[-0.69, 0, 25.93]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[1, 0.82, 0.14]}
              />
              <mesh
                name="Cube 132"
                geometry={nodes['Cube 132'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[-0.69, 0, -0.35]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[1, 0.85, 0.14]}
              />
              <mesh
                name="Cube 124"
                geometry={nodes['Cube 124'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[-0.69, 0, -26.88]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[1, 0.82, 0.14]}
              />
              <mesh
                name="Cube 113"
                geometry={nodes['Cube 113'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[-0.69, 0, -52.48]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[1, 0.82, 0.14]}
              />
              <mesh
                name="Cube 103"
                geometry={nodes['Cube 103'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[-0.69, 0, -108.37]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[1, 0.85, 0.14]}
              />
            </group>
            <group name="Group 3" position={[-119.73, 14.49, 8.35]} scale={[1, 1, 0.97]}>
              <mesh
                name="Cube 96"
                geometry={nodes['Cube 96'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[0.69, 0, -79.3]}
                rotation={[-Math.PI / 2, 1.57, 0]}
                scale={[1, 0.85, 0.14]}
              />
              <mesh
                name="Cube 74"
                geometry={nodes['Cube 74'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[0.69, 0, 105.01]}
                rotation={[-Math.PI / 2, 1.57, 0]}
                scale={[1, 0.85, 0.14]}
              />
              <mesh
                name="Cube 163"
                geometry={nodes['Cube 163'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[-0.69, 0, 78.22]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[1, 0.82, 0.14]}
              />
              <mesh
                name="Cube 154"
                geometry={nodes['Cube 154'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[-0.69, 0, 52.22]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[1, 0.82, 0.14]}
              />
              <mesh
                name="Cube 143"
                geometry={nodes['Cube 143'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[-0.69, 0, 25.93]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[1, 0.82, 0.14]}
              />
              <mesh
                name="Cube 133"
                geometry={nodes['Cube 133'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[-0.69, 0, -0.35]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[1, 0.85, 0.14]}
              />
              <mesh
                name="Cube 125"
                geometry={nodes['Cube 125'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[-0.69, 0, -26.88]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[1, 0.82, 0.14]}
              />
              <mesh
                name="Cube 114"
                geometry={nodes['Cube 114'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[-0.69, 0, -52.48]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[1, 0.82, 0.14]}
              />
              <mesh
                name="Cube 104"
                geometry={nodes['Cube 104'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[-0.69, 0, -108.37]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[1, 0.85, 0.14]}
              />
            </group>
            <mesh
              name="Cube 115"
              geometry={nodes['Cube 115'].geometry}
              material={materials['Train Color 1']}
              castShadow
              receiveShadow
              position={[-222.03, -8.96, -68.53]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.82, 1]}
            />
            <mesh
              name="Cube 97"
              geometry={nodes['Cube 97'].geometry}
              material={materials['Train Color 1']}
              castShadow
              receiveShadow
              position={[-120.33, -8.96, -68.53]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.82, 1]}
            />
            <mesh
              name="Cube 116"
              geometry={nodes['Cube 116'].geometry}
              material={materials['Train Color 1']}
              castShadow
              receiveShadow
              position={[-222.03, -8.96, 110.32]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.82, 1]}
            />
            <mesh
              name="Cube 55"
              geometry={nodes['Cube 55'].geometry}
              material={materials['Train Color 1']}
              castShadow
              receiveShadow
              position={[-120.33, -8.96, 110.32]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.82, 1]}
            />
            <mesh
              name="Cube 413"
              geometry={nodes['Cube 413'].geometry}
              material={materials['Train Top']}
              castShadow
              receiveShadow
              position={[-171.38, 30.19, -0.19]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={0.99}
            />
            <mesh
              name="Cube 105"
              geometry={nodes['Cube 105'].geometry}
              material={materials['Train Color 1']}
              castShadow
              receiveShadow
              position={[-171.38, 36.69, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={1}
            />
            <mesh
              name="Cube 314"
              geometry={nodes['Cube 314'].geometry}
              material={materials['Train Color 1']}
              castShadow
              receiveShadow
              position={[-171.38, 13.95, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={1}
            />
            <mesh
              name="Cylinder 4"
              geometry={nodes['Cylinder 4'].geometry}
              material={materials['Train Wheels']}
              castShadow
              receiveShadow
              position={[-171.55, -45.51, 84.21]}
              rotation={[0, 0, Math.PI / 2]}
              scale={[0.9, 4.65, 0.9]}
            />
            <mesh
              name="Cylinder 21"
              geometry={nodes['Cylinder 21'].geometry}
              material={materials['Train Wheels']}
              castShadow
              receiveShadow
              position={[-171.55, -45.51, -90.37]}
              rotation={[0, 0, Math.PI / 2]}
              scale={[0.9, 4.65, 0.9]}
            />
            <mesh
              name="Cylinder 31"
              geometry={nodes['Cylinder 31'].geometry}
              material={materials['Train Wheels']}
              castShadow
              receiveShadow
              position={[-171.55, -45.51, 66.45]}
              rotation={[0, 0, Math.PI / 2]}
              scale={[0.9, 4.65, 0.9]}
            />
            <mesh
              name="Cylinder7"
              geometry={nodes.Cylinder7.geometry}
              material={materials['Train Wheels']}
              castShadow
              receiveShadow
              position={[-171.55, -45.51, -108.14]}
              rotation={[0, 0, Math.PI / 2]}
              scale={[0.9, 4.65, 0.9]}
            />
            <mesh
              name="Cube14"
              geometry={nodes.Cube14.geometry}
              material={materials['Cube14 Material']}
              castShadow
              receiveShadow
              position={[-171.55, 0.24, -0.36]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[0.68, 0.68, 0.41]}
            />
          </group>
          <group name="Group 6" position={[-625.87, 156.59, -69.59]} rotation={[Math.PI / 2, -0.17, 0]} scale={1}>
            <mesh
              name="Cube 414"
              geometry={nodes['Cube 414'].geometry}
              material={materials['Train Windows']}
              castShadow
              receiveShadow
              position={[-170.56, 12.78, -128.52]}
              rotation={[0, 0, 0]}
            />
            <mesh
              name="Cube 315"
              geometry={nodes['Cube 315'].geometry}
              material={materials['Train Windows']}
              castShadow
              receiveShadow
              position={[-170.56, 12.78, 128.12]}
              rotation={[0, 0, 0]}
            />
            <group name="Group 51" position={[-222.15, 14.49, 8.35]} rotation={[0, 0, 0]} scale={[1, 1, 0.97]}>
              <mesh
                name="Cube 98"
                geometry={nodes['Cube 98'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[-2.78, 0, -79.3]}
                rotation={[-Math.PI / 2, 1.57, 0]}
                scale={[1, 0.85, 0.14]}
              />
              <mesh
                name="Cube 75"
                geometry={nodes['Cube 75'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[-2.78, 0, 105.01]}
                rotation={[-Math.PI / 2, 1.57, 0]}
                scale={[1, 0.85, 0.14]}
              />
              <mesh
                name="Cube 164"
                geometry={nodes['Cube 164'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[-0.69, 0, 78.22]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[1, 0.82, 0.14]}
              />
              <mesh
                name="Cube 155"
                geometry={nodes['Cube 155'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[-0.69, 0, 52.22]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[1, 0.82, 0.14]}
              />
              <mesh
                name="Cube 144"
                geometry={nodes['Cube 144'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[-0.69, 0, 25.93]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[1, 0.82, 0.14]}
              />
              <mesh
                name="Cube 134"
                geometry={nodes['Cube 134'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[-0.69, 0, -0.35]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[1, 0.85, 0.14]}
              />
              <mesh
                name="Cube 126"
                geometry={nodes['Cube 126'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[-0.69, 0, -26.88]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[1, 0.82, 0.14]}
              />
              <mesh
                name="Cube 117"
                geometry={nodes['Cube 117'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[-0.69, 0, -52.48]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[1, 0.82, 0.14]}
              />
              <mesh
                name="Cube 106"
                geometry={nodes['Cube 106'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[-0.69, 0, -108.37]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[1, 0.85, 0.14]}
              />
            </group>
            <group name="Group 31" position={[-119.73, 14.49, 8.35]} scale={[1, 1, 0.97]}>
              <mesh
                name="Cube 99"
                geometry={nodes['Cube 99'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[0.69, 0, -79.3]}
                rotation={[-Math.PI / 2, 1.57, 0]}
                scale={[1, 0.85, 0.14]}
              />
              <mesh
                name="Cube 76"
                geometry={nodes['Cube 76'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[0.69, 0, 105.01]}
                rotation={[-Math.PI / 2, 1.57, 0]}
                scale={[1, 0.85, 0.14]}
              />
              <mesh
                name="Cube 165"
                geometry={nodes['Cube 165'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[-0.69, 0, 78.22]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[1, 0.82, 0.14]}
              />
              <mesh
                name="Cube 156"
                geometry={nodes['Cube 156'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[-0.69, 0, 52.22]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[1, 0.82, 0.14]}
              />
              <mesh
                name="Cube 145"
                geometry={nodes['Cube 145'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[-0.69, 0, 25.93]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[1, 0.82, 0.14]}
              />
              <mesh
                name="Cube 135"
                geometry={nodes['Cube 135'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[-0.69, 0, -0.35]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[1, 0.85, 0.14]}
              />
              <mesh
                name="Cube 127"
                geometry={nodes['Cube 127'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[-0.69, 0, -26.88]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[1, 0.82, 0.14]}
              />
              <mesh
                name="Cube 118"
                geometry={nodes['Cube 118'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[-0.69, 0, -52.48]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[1, 0.82, 0.14]}
              />
              <mesh
                name="Cube 107"
                geometry={nodes['Cube 107'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[-0.69, 0, -108.37]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[1, 0.85, 0.14]}
              />
            </group>
            <mesh
              name="Cube 119"
              geometry={nodes['Cube 119'].geometry}
              material={materials['Train Color 1']}
              castShadow
              receiveShadow
              position={[-222.03, -8.96, -68.53]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.82, 1]}
            />
            <mesh
              name="Cube 910"
              geometry={nodes['Cube 910'].geometry}
              material={materials['Train Color 1']}
              castShadow
              receiveShadow
              position={[-120.33, -8.96, -68.53]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.82, 1]}
            />
            <mesh
              name="Cube 1110"
              geometry={nodes['Cube 1110'].geometry}
              material={materials['Train Color 1']}
              castShadow
              receiveShadow
              position={[-222.03, -8.96, 110.32]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.82, 1]}
            />
            <mesh
              name="Cube 56"
              geometry={nodes['Cube 56'].geometry}
              material={materials['Train Color 1']}
              castShadow
              receiveShadow
              position={[-120.33, -8.96, 110.32]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.82, 1]}
            />
            <mesh
              name="Cube 415"
              geometry={nodes['Cube 415'].geometry}
              material={materials['Train Top']}
              castShadow
              receiveShadow
              position={[-171.38, 30.19, -0.19]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={0.99}
            />
            <mesh
              name="Cube 108"
              geometry={nodes['Cube 108'].geometry}
              material={materials['Train Color 1']}
              castShadow
              receiveShadow
              position={[-171.38, 36.69, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={1}
            />
            <mesh
              name="Cube 316"
              geometry={nodes['Cube 316'].geometry}
              material={materials['Train Color 1']}
              castShadow
              receiveShadow
              position={[-171.38, 13.95, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={1}
            />
            <mesh
              name="Cylinder 41"
              geometry={nodes['Cylinder 41'].geometry}
              material={materials['Train Wheels']}
              castShadow
              receiveShadow
              position={[-171.55, -45.51, 84.21]}
              rotation={[0, 0, Math.PI / 2]}
              scale={[0.9, 4.65, 0.9]}
            />
            <mesh
              name="Cylinder 22"
              geometry={nodes['Cylinder 22'].geometry}
              material={materials['Train Wheels']}
              castShadow
              receiveShadow
              position={[-171.55, -45.51, -90.37]}
              rotation={[0, 0, Math.PI / 2]}
              scale={[0.9, 4.65, 0.9]}
            />
            <mesh
              name="Cylinder 32"
              geometry={nodes['Cylinder 32'].geometry}
              material={materials['Train Wheels']}
              castShadow
              receiveShadow
              position={[-171.55, -45.51, 66.45]}
              rotation={[0, 0, Math.PI / 2]}
              scale={[0.9, 4.65, 0.9]}
            />
            <mesh
              name="Cylinder8"
              geometry={nodes.Cylinder8.geometry}
              material={materials['Train Wheels']}
              castShadow
              receiveShadow
              position={[-171.55, -45.51, -108.14]}
              rotation={[0, 0, Math.PI / 2]}
              scale={[0.9, 4.65, 0.9]}
            />
            <mesh
              name="Cube15"
              geometry={nodes.Cube15.geometry}
              material={materials['Cube15 Material']}
              castShadow
              receiveShadow
              position={[-171.55, 0.24, -0.36]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[0.68, 0.68, 0.41]}
            />
          </group>
          <group name="Group 52" position={[-636.44, -78.53, -69.59]} rotation={[Math.PI / 2, 0.09, 0]} scale={1}>
            <mesh
              name="Cube 416"
              geometry={nodes['Cube 416'].geometry}
              material={materials['Train Windows']}
              castShadow
              receiveShadow
              position={[-170.56, 12.78, -128.52]}
              rotation={[0, 0, 0]}
            />
            <mesh
              name="Cube 317"
              geometry={nodes['Cube 317'].geometry}
              material={materials['Train Windows']}
              castShadow
              receiveShadow
              position={[-170.56, 12.78, 128.12]}
              rotation={[0, 0, 0]}
            />
            <group name="Group 53" position={[-222.26, 14.49, 8.35]} rotation={[0, 0, 0]} scale={[1, 1, 0.97]}>
              <mesh
                name="Cube 911"
                geometry={nodes['Cube 911'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[-2.78, 0, -79.3]}
                rotation={[-Math.PI / 2, 1.57, 0]}
                scale={[1, 0.85, 0.14]}
              />
              <mesh
                name="Cube 77"
                geometry={nodes['Cube 77'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[-2.78, 0, 105.01]}
                rotation={[-Math.PI / 2, 1.57, 0]}
                scale={[1, 0.85, 0.14]}
              />
              <mesh
                name="Cube 166"
                geometry={nodes['Cube 166'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[-0.69, 0, 78.22]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[1, 0.82, 0.14]}
              />
              <mesh
                name="Cube 157"
                geometry={nodes['Cube 157'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[-0.69, 0, 52.22]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[1, 0.82, 0.14]}
              />
              <mesh
                name="Cube 146"
                geometry={nodes['Cube 146'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[-0.69, 0, 25.93]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[1, 0.82, 0.14]}
              />
              <mesh
                name="Cube 136"
                geometry={nodes['Cube 136'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[-0.69, 0, -0.35]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[1, 0.85, 0.14]}
              />
              <mesh
                name="Cube 128"
                geometry={nodes['Cube 128'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[-0.69, 0, -26.88]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[1, 0.82, 0.14]}
              />
              <mesh
                name="Cube 1111"
                geometry={nodes['Cube 1111'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[-0.69, 0, -52.48]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[1, 0.82, 0.14]}
              />
              <mesh
                name="Cube 109"
                geometry={nodes['Cube 109'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[-0.69, 0, -108.37]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[1, 0.85, 0.14]}
              />
            </group>
            <group name="Group 32" position={[-119.73, 14.49, 8.35]} scale={[1, 1, 0.97]}>
              <mesh
                name="Cube 912"
                geometry={nodes['Cube 912'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[0.69, 0, -79.3]}
                rotation={[-Math.PI / 2, 1.57, 0]}
                scale={[1, 0.85, 0.14]}
              />
              <mesh
                name="Cube 78"
                geometry={nodes['Cube 78'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[0.69, 0, 105.01]}
                rotation={[-Math.PI / 2, 1.57, 0]}
                scale={[1, 0.85, 0.14]}
              />
              <mesh
                name="Cube 167"
                geometry={nodes['Cube 167'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[-0.69, 0, 78.22]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[1, 0.82, 0.14]}
              />
              <mesh
                name="Cube 158"
                geometry={nodes['Cube 158'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[-0.69, 0, 52.22]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[1, 0.82, 0.14]}
              />
              <mesh
                name="Cube 147"
                geometry={nodes['Cube 147'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[-0.69, 0, 25.93]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[1, 0.82, 0.14]}
              />
              <mesh
                name="Cube 137"
                geometry={nodes['Cube 137'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[-0.69, 0, -0.35]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[1, 0.85, 0.14]}
              />
              <mesh
                name="Cube 129"
                geometry={nodes['Cube 129'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[-0.69, 0, -26.88]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[1, 0.82, 0.14]}
              />
              <mesh
                name="Cube 1112"
                geometry={nodes['Cube 1112'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[-0.69, 0, -52.48]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[1, 0.82, 0.14]}
              />
              <mesh
                name="Cube 1010"
                geometry={nodes['Cube 1010'].geometry}
                material={materials['Train Windows']}
                castShadow
                receiveShadow
                position={[-0.69, 0, -108.37]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[1, 0.85, 0.14]}
              />
            </group>
            <mesh
              name="Cube 1113"
              geometry={nodes['Cube 1113'].geometry}
              material={materials['Train Color 1']}
              castShadow
              receiveShadow
              position={[-222.03, -8.96, -68.53]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.82, 1]}
            />
            <mesh
              name="Cube 913"
              geometry={nodes['Cube 913'].geometry}
              material={materials['Train Color 1']}
              castShadow
              receiveShadow
              position={[-120.33, -8.96, -68.53]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.82, 1]}
            />
            <mesh
              name="Cube 1114"
              geometry={nodes['Cube 1114'].geometry}
              material={materials['Train Color 1']}
              castShadow
              receiveShadow
              position={[-222.03, -8.96, 110.32]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.82, 1]}
            />
            <mesh
              name="Cube 57"
              geometry={nodes['Cube 57'].geometry}
              material={materials['Train Color 1']}
              castShadow
              receiveShadow
              position={[-120.33, -8.96, 110.32]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 0.82, 1]}
            />
            <mesh
              name="Cube 417"
              geometry={nodes['Cube 417'].geometry}
              material={materials['Train Top']}
              castShadow
              receiveShadow
              position={[-171.38, 30.19, -0.19]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={0.99}
            />
            <mesh
              name="Cube 1011"
              geometry={nodes['Cube 1011'].geometry}
              material={materials['Train Color 1']}
              castShadow
              receiveShadow
              position={[-171.38, 36.69, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={1}
            />
            <mesh
              name="Cube 318"
              geometry={nodes['Cube 318'].geometry}
              material={materials['Train Color 1']}
              castShadow
              receiveShadow
              position={[-171.38, 13.95, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={1}
            />
            <mesh
              name="Cylinder 42"
              geometry={nodes['Cylinder 42'].geometry}
              material={materials['Train Wheels']}
              castShadow
              receiveShadow
              position={[-171.55, -45.51, 84.21]}
              rotation={[0, 0, Math.PI / 2]}
              scale={[0.9, 4.65, 0.9]}
            />
            <mesh
              name="Cylinder 23"
              geometry={nodes['Cylinder 23'].geometry}
              material={materials['Train Wheels']}
              castShadow
              receiveShadow
              position={[-171.55, -45.51, -90.37]}
              rotation={[0, 0, Math.PI / 2]}
              scale={[0.9, 4.65, 0.9]}
            />
            <mesh
              name="Cylinder 33"
              geometry={nodes['Cylinder 33'].geometry}
              material={materials['Train Wheels']}
              castShadow
              receiveShadow
              position={[-171.55, -45.51, 66.45]}
              rotation={[0, 0, Math.PI / 2]}
              scale={[0.9, 4.65, 0.9]}
            />
            <mesh
              name="Cylinder9"
              geometry={nodes.Cylinder9.geometry}
              material={materials['Train Wheels']}
              castShadow
              receiveShadow
              position={[-171.55, -45.51, -108.14]}
              rotation={[0, 0, Math.PI / 2]}
              scale={[0.9, 4.65, 0.9]}
            />
            <mesh
              name="Cube16"
              geometry={nodes.Cube16.geometry}
              material={materials['Cube16 Material']}
              castShadow
              receiveShadow
              position={[-171.55, 0.24, -0.36]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[0.68, 0.68, 0.41]}
            />
          </group>
        </mesh>
        <group name="Light Post" position={[446.43, 572.89, -308.91]}>
          <mesh
            name="Cylinder 43"
            geometry={nodes['Cylinder 43'].geometry}
            material={materials['']}
            castShadow
            receiveShadow
            position={[1.16, 246.4, 0.34]}
            rotation={[0, -0.75, 0]}
            scale={1.27}
          />
          <group name="Group" position={[1.68, 249.83, -0.29]} rotation={[0, 0, 0]} scale={1.27}>
            <mesh
              name="Cube 83"
              geometry={nodes['Cube 83'].geometry}
              material={materials['Concrete/Stones']}
              castShadow
              receiveShadow
              position={[-36.3, 0, -33.6]}
              rotation={[-Math.PI / 2, 0, -2.3]}
              scale={[-0.58, 0.58, 3.74]}
            />
            <mesh
              name="Cube 79"
              geometry={nodes['Cube 79'].geometry}
              material={materials['Concrete/Stones']}
              castShadow
              receiveShadow
              position={[-49.75, 0, 1.78]}
              rotation={[-Math.PI / 2, 0, -1.61]}
              scale={[-0.58, 0.58, 3.74]}
            />
            <mesh
              name="Cube 63"
              geometry={nodes['Cube 63'].geometry}
              material={materials['Concrete/Stones']}
              castShadow
              receiveShadow
              position={[-33.49, 0, 36.35]}
              rotation={[-Math.PI / 2, 0, -0.91]}
              scale={[-0.58, 0.58, 3.74]}
            />
            <mesh
              name="Cube 58"
              geometry={nodes['Cube 58'].geometry}
              material={materials['Concrete/Stones']}
              castShadow
              receiveShadow
              position={[1.91, 0, 49.89]}
              rotation={[-Math.PI / 2, 0, -0.03]}
              scale={[-0.58, 0.58, 3.74]}
            />
            <mesh
              name="Cube 418"
              geometry={nodes['Cube 418'].geometry}
              material={materials['Concrete/Stones']}
              castShadow
              receiveShadow
              position={[36.46, 0, 34.66]}
              rotation={[-Math.PI / 2, 0, 0.75]}
              scale={[-0.58, 0.58, 3.74]}
            />
            <mesh
              name="Cube 319"
              geometry={nodes['Cube 319'].geometry}
              material={materials['Concrete/Stones']}
              castShadow
              receiveShadow
              position={[49.72, 0, -1.51]}
              rotation={[-Math.PI / 2, 0, 1.62]}
              scale={[-0.58, 0.58, 3.74]}
            />
            <mesh
              name="Cube 217"
              geometry={nodes['Cube 217'].geometry}
              material={materials['Concrete/Stones']}
              castShadow
              receiveShadow
              position={[34.25, 0, -36.39]}
              rotation={[-Math.PI / 2, 0, 2.41]}
              scale={[-0.58, 0.58, 3.74]}
            />
            <mesh
              name="Cube17"
              geometry={nodes.Cube17.geometry}
              material={materials['Concrete/Stones']}
              castShadow
              receiveShadow
              position={[-2.13, 0, -49.25]}
              rotation={[-Math.PI / 2, 0, 2.23]}
              scale={[-0.58, 0.58, 3.74]}
            />
          </group>
          <mesh
            name="Cylinder 5"
            geometry={nodes['Cylinder 5'].geometry}
            material={materials['Cylinder 5 Material']}
            castShadow
            receiveShadow
            position={[1.35, 297.95, 0.61]}
            rotation={[-Math.PI, 0.75, -Math.PI]}
            scale={[-0.73, 0.73, 0.73]}
          />
          <group name="Group1" position={[0.27, 210.44, 0.98]}>
            <mesh
              name="Cube 84"
              geometry={nodes['Cube 84'].geometry}
              material={materials['House Borders']}
              castShadow
              receiveShadow
              position={[-62.63, 0, -58.57]}
              rotation={[-Math.PI / 2, 0, -2.34]}
              scale={1}
            />
            <mesh
              name="Cube 710"
              geometry={nodes['Cube 710'].geometry}
              material={materials['House Borders']}
              castShadow
              receiveShadow
              position={[-3.04, 0, -86.11]}
              rotation={[-Math.PI / 2, 0, -3.04]}
              scale={1}
            />
            <mesh
              name="Cube 64"
              geometry={nodes['Cube 64'].geometry}
              material={materials['House Borders']}
              castShadow
              receiveShadow
              position={[58.73, 0, -62.17]}
              rotation={[-Math.PI / 2, 0, 2.55]}
              scale={1}
            />
            <mesh
              name="Cube 59"
              geometry={nodes['Cube 59'].geometry}
              material={materials['House Borders']}
              castShadow
              receiveShadow
              position={[86.44, 0, -2.57]}
              rotation={[-Math.PI / 2, 0, 1.68]}
              scale={1}
            />
            <mesh
              name="Cube 419"
              geometry={nodes['Cube 419'].geometry}
              material={materials['House Borders']}
              castShadow
              receiveShadow
              position={[64.26, 0, 59.05]}
              rotation={[-Math.PI / 2, 0, 0.89]}
              scale={1}
            />
            <mesh
              name="Cube 320"
              geometry={nodes['Cube 320'].geometry}
              material={materials['House Borders']}
              castShadow
              receiveShadow
              position={[3.3, 0, 86.35]}
              rotation={[-Math.PI / 2, 0, 0.02]}
              scale={1}
            />
            <mesh
              name="Cube 218"
              geometry={nodes['Cube 218'].geometry}
              material={materials['House Borders']}
              castShadow
              receiveShadow
              position={[-58.91, 0, 63.81]}
              rotation={[-Math.PI / 2, 0, -0.77]}
              scale={1}
            />
            <mesh
              name="Cube18"
              geometry={nodes.Cube18.geometry}
              material={materials['House Borders']}
              castShadow
              receiveShadow
              position={[-85.57, 0, 2.43]}
              rotation={[-Math.PI / 2, 0, -0.59]}
              scale={1}
            />
          </group>
          <mesh
            name="Cylinder 34"
            geometry={nodes['Cylinder 34'].geometry}
            material={materials['']}
            castShadow
            receiveShadow
            position={[0.47, 217.98, 2.02]}
            rotation={[0, -0.75, 0]}
          />
          <mesh
            name="Cylinder 24"
            geometry={nodes['Cylinder 24'].geometry}
            material={materials['Concrete/Stones']}
            castShadow
            receiveShadow
            position={[0, -192.97, 0]}
            rotation={[0, -0.75, 0]}
            scale={0.85}
          />
          <mesh
            name="Cylinder10"
            geometry={nodes.Cylinder10.geometry}
            material={materials['']}
            castShadow
            receiveShadow
            position={[-0.29, -265.64, 0.31]}
            rotation={[0, -0.75, 0]}
            scale={0.85}
          />
        </group>
        <mesh
          name="Train Rail 1"
          geometry={nodes['Train Rail 1'].geometry}
          material={materials['Train Rail 1 Material']}
          castShadow
          receiveShadow
          position={[-15.53, -70.22, 51.2]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          name="Train Rail 2"
          geometry={nodes['Train Rail 2'].geometry}
          material={materials['Train Rail 2 Material']}
          castShadow
          receiveShadow
          position={[-15.53, -70.62, 51.2]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          name="Train Rail Base"
          geometry={nodes['Train Rail Base'].geometry}
          material={materials['Train Rail Base Material']}
          castShadow
          receiveShadow
          position={[-15.53, -74.62, 51.2]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          name="Island Grass"
          geometry={nodes['Island Grass'].geometry}
          material={materials.Grass}
          castShadow
          receiveShadow
          position={[-296.64, 154.08, -282.89]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={[1.27, 1.29, 1.4]}
        />
        <mesh
          name="Island Rock Base"
          geometry={nodes['Island Rock Base'].geometry}
          material={materials['Island Rock Base Material']}
          castShadow
          receiveShadow
          position={[-299.35, 122.9, -282.89]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={1.31}
        />
        <directionalLight
          name="Directional Light"
          castShadow
          intensity={0.6}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={-10000}
          shadow-camera-far={100000}
          shadow-camera-left={-1954.0265}
          shadow-camera-right={1954.0265}
          shadow-camera-top={1954.0265}
          shadow-camera-bottom={-1954.0265}
          color="#fefaf6"
          position={[689.09, 850.57, 401.6]}
        />
        <OrthographicCamera name="1" makeDefault={true} zoom={0.4} far={100000} near={-100000} position={[0, -210, 1000]} rotation={[0, 0, 0]} />
        <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" />
      </group>
    </>
  )
}
